spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/
    driverClassName: com.mysql.cj.jdbc.Driver
    password: Mysql26!
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.SQLServer2012Dialect
      ddl-auto: create-drop
    show-sql: 'true'
