spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/HospitalDB
    driverClassName: com.mysql.cj.jdbc.Driver
    password: Mysql26!
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 10MB
      max-request-size: 15MB

  jpa:
    hibernate:
      dialect: org.hibernate.dialect.SQLServer2012Dialect
      ddl-auto: create-drop
    show-sql: 'true'

server:
  port: 8081


